// <auto-generated />
using System;
using APEC.WS.Infrastructura.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APEC.WSPublicos.Infrastructura.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("APEC.WS.Infrastructura.Modelos.Cliente", b =>
                {
                    b.Property<string>("CedulaRnc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<char>("IndicadorSalud")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoTotalAdeudado")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CedulaRnc");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("APEC.WS.Infrastructura.Modelos.HistorialCrediticio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClienteCedulaRnc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConceptoDeuda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontoAdeudado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RncEmpresa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCedulaRnc");

                    b.ToTable("HistorialesCrediticios");
                });

            modelBuilder.Entity("APEC.WS.Infrastructura.Modelos.IndiceInflacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("IndicesInflacion");
                });

            modelBuilder.Entity("APEC.WS.Infrastructura.Modelos.RegistroUsoServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaInvocacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RegistrosUso");
                });

            modelBuilder.Entity("APEC.WS.Infrastructura.Modelos.TasaCambiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoMoneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("TasasCambiarias");
                });

            modelBuilder.Entity("APEC.WS.Infrastructura.Modelos.HistorialCrediticio", b =>
                {
                    b.HasOne("APEC.WS.Infrastructura.Modelos.Cliente", "Cliente")
                        .WithMany("Historiales")
                        .HasForeignKey("ClienteCedulaRnc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("APEC.WS.Infrastructura.Modelos.Cliente", b =>
                {
                    b.Navigation("Historiales");
                });
#pragma warning restore 612, 618
        }
    }
}
